### ISSUE TITLE
Could you share the data used in main_gan_mod.ipynb?

### ISSUE THREAD

**Issue by Rowing0914** [rushhan/Generative-Adversarial-User-Model-for-Reinforcement-Learning-Based-Recommendation-System-Pytorch#1]
I love your project! If possible, could you share the data you used in `main_gan_mod.ipynb`?
I'd like to follow the notebook using your data!!

**Comment by rushhan** [comment]
Sorry about that. The file had nothing to do with the current project.  
As for main_gan_mod.ipynb, I am still working on it and I will upload it again after I am able to improve the results.

**Comment by Rowing0914** [comment]
Thank you for your prompt response!
Looking forward to your update!!
