### ISSUE TITLE
about source dataset yelp.txt

### ISSUE THREAD

**Issue by zepengfang** [rushhan/Generative-Adversarial-User-Model-for-Reinforcement-Learning-Based-Recommendation-System-Pytorch#2]
hello, how can I get the dataset "yelp.txt" you use in the experiment? Can you upload it too?
=>preprocess_data.py / filename = opts.data_folder+opts.dataset+'.txt'

**Comment by strive-man** [comment]
hello, how can I get the dataset "yelp.txt" you use in the experiment? Can you upload it too?

**Comment by rushhan** [comment]
I added it, but don't think it's necessary for this project. pkl file should suffice.
